### ISSUE TITLE
[EPIC] Segment Histories Over Time graph is all kinds of messed up

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#271]
Progress list:
- [ ] Run IDs are ignored
- [ ] Lines should not be forced to start at attempt 1
- [ ] Skipped/new splits parse as 0:00:00
- [ ] Some (one) attempts appear twice

See https://splits.io/13gy/stats for all references below.

# Problem 1 (the big one): Run IDs are ignored
Either the parser or something about the stats page specifically is parsing segment/run histories incorrectly. Taking a look at the first split (Spirit Flame) on the Segment Histories Over Time graph shows us that the first attempt was a 1:04, the second a 1:05, and the third a 1:04.
![image](https://cloud.githubusercontent.com/assets/1765799/22352974/52504636-e3ec-11e6-98ac-bc79c86bbc6a.png)
However, in the splits file, attempts one and _two_ are both 1:04s and attempt _three_ is the 1:05.
![image](https://cloud.githubusercontent.com/assets/1765799/22353017/84b33d22-e3ec-11e6-92d1-e9c75c2ad988.png)
Don't ask me why, but LiveSplit can apparently save segment histories out of order (_wtf LiveSplit..._) and it looks like splits.io is ignoring the ID during parsing and simply parsing in order. It should check the ID.
**This is likely affecting the Run Duration Over Time graph and possibly others as well.**

## Corollary: Graphs always start at the first attempt, even if the segment wasn't present
Each individual data point should show at its correct attempt number, even if this means graph lines start at different points on the _x_ axis. Floating lines _should be ok._
![image](https://cloud.githubusercontent.com/assets/1765799/22353904/bececc16-e3f0-11e6-98a3-77da94b3314c.png)
_This split was skipped in the first attempt, so the line should start at attempt 2._

# Problem 2: Skipped splits are parsed as 0:00:00
Splits that are blank for an attempt (either due to skipping **or** from adding the split in after some attempts/runs have already been made) are being parsed as 0:00:00, drastically throwing off the graph.
![image](https://cloud.githubusercontent.com/assets/1765799/22353165/2b064b9c-e3ed-11e6-990a-8e7931ed4e22.png)
_Note that all of the highlighted segments start at 0 because they were skipped in the first attempt._

It's even worse for new splits because they'll show a 0:00:00 for every attempt (_**and**_ the attempt numbers are being incorrectly parsed due to problem 1).
![image](https://cloud.githubusercontent.com/assets/1765799/22353280/b977d6b6-e3ed-11e6-85e5-7db708469be2.png)
_Note how Exit Misty skews the graph height by showing all 0:00:00 for several attempts because it was added to the splits after several attempts had already been made._

In the splits file skipped/new splits show blank, not 0:00:00, so it should be possible to differentiate between _actual_ 0:00:00 splits and skipped ones.
![image](https://cloud.githubusercontent.com/assets/1765799/22353594/400f7fa2-e3ef-11e6-952e-4a1811c8b593.png)

# Problem 3: One attempt shows up twice
No fucking idea on this one. **Only** attempt 26 as far as I can tell. Remember that this is actually the _incorrect_ attempt 26 to begin with due to problem 1. I guess I wouldn't be surprised if the added split (Exit Misty) has something to do with it since it was added just before upload and ends at the first 26.
[Example GIF](https://i.gyazo.com/9f163c7e4504b05bf6022005c7e9c874.mp4)

**Comment by glacials** [comment]
Amazing report! 💥 

### 1: Out of order attempts
This shouldn't actually be much work -- I've recently moved some other pieces of code over to using history maps like `{1: <time>, 2: <time>}` instead of `[<time>, <time>]` just to improve code quality in the [`dynamodb_history`][1] branch so I just need to finish that up and have the graphs use it.

[1]: https://github.com/glacials/splits-io/tree/dynamodb_history

### 2: Skipped splits showing as 0:00:00
Haha this is a pretty funny anachronism from before LiveSplit existed and WSplit was still the timer of choice, as it actually *did* store skipped splits as 0:00:00, so I carried that through into Splits I/O. I totally agree they should be two different concepts. Quick fix could be to just treat 0s as null on the frontend, but the proper thing to do here is to make this change in the run parsers.

### 3: Duplicated attempts
?????????????????????????????

I'll have to look at this one more closely lol.

**Comment by glacials** [comment]
Okay, I believe I've fixed all the issues listed. Charts are now powered by attempt ID, not order, and skipped splits are treated as null, not 0, on the y-axis. This applies to the run history graph and the segment history graph, which use basically the same code now.

I didn't actually investigate the duplicated attempts issue as it was fixed by the refactor to run IDs. I'm guessing it was caused by the fact that the different segment lines' attempt numbers weren't aligned with each other.

To see the changes on runs that already exist you may need to add `?reparse=1` to the end of its URL once. Either way they'll be refreshed eventually.

Can you confirm you're seeing what you expect?

**Comment by BatedUrGonnaDie** [comment]
Was the timeline broken on the stats page before these changes?  It no longer lines up visually with where the indicated splits are on hovering but on the main run page it's correct.

**Comment by jhobz** [comment]
@glacials The run history & segment history graphs both seem to be correct now, although the resets per split graph seems to have broken as a result. Also, now that I see the disjointed graphs in action, I'm thinking maybe it wasn't the best suggestion. Would it make more sense to connect disjointed data points by a dashed line or something (if that's possible)? Or possibly even just connect them with solid lines. I'm also not sure what's going on in the segment graph here: https://splits.io/13mq/stats, unless Grim actually deleted his split history or something. May want to start the graph at the first attempt that has a data point for at least one segment.

@BatedUrGonnaDie Unfortunately, I don't know if it was broken before or not. It doesn't appear to be broken on all (see https://splits.io/13mq/stats), so maybe it's based on number of splits or something?

**Comment by glacials** [comment]
@BatedUrGonnaDie: Can you link a run where you know this happens? I don't see one, but I've seen some Turbolinks weirdness in the timeline when transitioning from a run page to a stats page (but not on a hard refresh of the stats page), so maybe it's similar.

@jhobz: Opening up Grim's run, yeah his segments' histories start at run 649 -- there's no history before that. I'm assuming the splits are older than LiveSplit's segment history feature. Agree, we can start the graph at the first non-null entry.

I went ahead and added lines connecting all disjointed graph points. Looking at the C3 API dashed lines are possible but setting them up specifically to happen whenever there's a null entry seems like more work than is worth doing for my non-JS brain.

**Comment by BatedUrGonnaDie** [comment]
@glacials The run linked in the first post is the one that is messing up in both chrome and FF

**Comment by glacials** [comment]
Cool, fixed that bug in this ^ commit.

**Comment by BatedUrGonnaDie** [comment]
Sweet

**Comment by BatedUrGonnaDie** [comment]
@jhobz All the issues look like they're fixed, do you agree?

**Comment by jhobz** [comment]
Yep, looks good to me!
