### ISSUE TITLE
Rails 6 Compatibility Tracker

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [glacials/splits-io#517]
With Rails 6 release right around the corner on April 30th, this issue will serve as a would be tracker to make sure that we can upgrade as soon as possible to take advantage of the various changes and improvements.

### Gem dependencies
- [x] `active_model_serializers` - has a hard limit of < 6, there is a PR open to fix depreciation warning but does not change the gemspec definition from < 6.  If blueprinter adds root node support before rails 6 drops, then this could most likely just be dropped in favor of that pending more benchmarking.

- [x] `delayed_job_active_record` - has hard limit of < 6, but they have a Rails 6 beta branch that will most likely be merged in when rails 6 drops officially, so this really should be a problem.

- [x] `meta_request` - has hard limit of < 6, with no branch of PR's.  Last commit was April 2018 so this may or may not get updated.

- [x] `administrate` - has hard limit of < 6, with no branch or PR's.  I assume this will be updated once rails 6 officially dropped as commits are still frequent.

- [x] `rspec-rails` - throws lots of errors when running the test suite, attempting to upgrade it to dev branch at this time resulted in even more errors.

### Code Changes
After running the update task, there are a few changes that are known know.  [Source](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html)

- [ ] The new framework defaults are located in an initializer, these should be gone through one by one and made sure that they all work, then change the default config loadout.

- [ ] There is a new cookie option, we have had issue with this in the past so it should be double checked that this works properly in beta before approving.

- [x] ActionCable is now fully distributed in ES2015, which means we should update the code related to it to use proper imports.

- [x] Looks like `rails-ujs` npm package is now `@rails/ujs`.  Update this through yarn.

This is not a perfect list, just things that I was able to find at this stage.  ActiveRecord and ActiveSupport both had pretty lengthy changelogs as well.  They both removed and depreciated a lot things, but also added some cool new helper methods.  It may be worth while to go through what was added and see where we can use them to clean up old code to make it more readable/maintainable.

### Code Depreciations
As with every release, some things got depreciated.  These are not necessarily required to get rails 6 running, but we should take care of them as fast as possible so that we don't get into a situation where we're blocked by a dumb depreciation.  Once we start getting notices we can add them in this section to track them.

- [x] `force_ssl` in the controller is now depreciated, we use this in the API.

**Comment by BatedUrGonnaDie** [comment]
Currently this is blocked by authie not autoloading properly under zeitwerk.  A PR is open to fix it but have't heard anything back on it.
