### ISSUE TITLE
Transition Off Sprockets Tracker

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [glacials/splits-io#519]
We added the webpacker gem quite a while ago to allow us to write ES2015 javascript and utilize yarn better.  While all the new code has gone in there, there are still some left over files that need to be taken care of as well as some boils.

Most of these are independent of each other, so anyone wanting something small to start with can just knock one file out at a time.

### Migrate old javascript to webpacker
Most of the files need to be ported back to regular JS from CoffeeScript.  Some of the files are only a few lines, but some might require heavy modification.
- [x] `analytics.js`
- [x] `category_tabs.coffee`
- [x] `gon.coffee`
- [x] `run_delete.coffee`
- [x] `run_disown.coffee`
- [x] `spinner.coffee`
- [x] `splits_inspector.coffee`
- [x] `upload-menu.coffee`

### Remove global imports
All files in `app/javascript` should be exporting and importing functions as they need them instead of relying on packages being imported into the global namespace.
- [x] `moment`
- [x] `Spinner`
- [x] `Clipboard`
- [x] `Cookies`

### Refactor some code
Not all code living in webpacker now actually utilizes some useful functions introduced with ES2015.  We should go through and make sure all the code is up to date, and remove jQuery where possible to get to a point where dumping it when the dependencies remove it a quick transition.

**Comment by BatedUrGonnaDie** [comment]
f8af8e9525c2ec9dba804991e7f6ce3b00a73374 and 660b2ad3d4eff93f70d5efdb4bd1e9a47db2c7de closed the first 2 parts.  There might still be a bit of non-es6 code floating around but it should be very minimal if there is any.
